### ISSUE TITLE
Rules when false

### ISSUE THREAD

**Issue by hhummell81** [monooso/apposite#5]
Idea: What if we pass a third parameter in the constructor, so we can set rules when conditional is false?

For instance:

`
        'email'          => [
            new ApplyWhen($request->contact_method === 'email', ['required', 'email', 'max:255'], ['nullable']),
        ],
`

Without the third argument, email wouldn't be saved  if contact_method is not 'email'. But maybe is an optional contact method, even if the user selects phone.

Does that make sense to you?

**Comment by monooso** [comment]
@hhummell81 You can achieve this using a combination of `ApplyWhen` and `ApplyUnless`:

```php
$rules = [
    'email'  => [
        new ApplyWhen($request->contact_method === 'email', ['required', 'email', 'max:255']),
        new ApplyUnless($request->contact_method === 'email', ['nullable']),
    ]
];
```

**Comment by hhummell81** [comment]
Thanks for the tip!

P.S.: I still think it is cleaner with a third parameter, hehehe  :)

**Comment by monooso** [comment]
@hhummell81 I know what you mean, but it's a trade-off. I'd prefer to keep it simple, and utilise what's already there.
